# Site settings
title: DeLaney
email: gld1982ltd@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my awesome site on awesome stuff from around the web.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gld1982ltd.xyz" # the base hostname & protocol for your site
twitter_username: gld1982ltd
github_username:  gld1982ltd

# Build settings
markdown: kramdown
